apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-blue
  namespace: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      color: blue
  template:
    metadata:
      labels:
        app: web
        color: blue
    spec:
      containers:
      - name: app
        image: 590183682241.dkr.ecr.eu-west-2.amazonaws.com/devops-eks-cicd-app:latest
        env:
        - name: APP_COLOR
          value: "blue"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
