apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: web
spec:
  type: LoadBalancer
  selector:
    app: web
    color: blue
  ports:
  - name: http              # <— add this line
    port: 80
    targetPort: 8080
